version: "3"

services:
  # api_v5:
  #   build: ./
  #   image: yoloifmt_api:0.5.3
  #   command: python3 server.py --host 0.0.0.0
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - test_network

  api_v6:
    build: ./
    image: yoloifmt_api_yolov6:0.1
    command: python3 server.py --host 0.0.0.0 --port 8001
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8001:8001
    networks:
      - test_network

networks:
  test_network:
    driver: bridge