version: "3"

services:
  api:
    build: ./
    image: yoloifmt_api
    command: python3 server.py --host 0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
              capabilities: [gpu]
    ports:
      - 8000:8000
    networks:
      - test_network

networks:
  test_network:
    driver: bridge